In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://drive.usercontent.google.com/download?id=1iw4BfRDLl64v90eSxKFEvi9BHycp_P_R&export=download&authuser=0&confirm=t&uuid=558ba2a6-b4b6-4659-865b-fac3a5f69546&at=ANTm3cwMyZis6BHK_OnPPRcBdyjJ:1768488620929')

In [3]:
df

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence

# Data selection
### There various way for data selection(through index, loc,iloc,at,iat)

In [4]:
df[0:8]

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
5,65,1,4,120,177,0,0,140,0,0.4,1,0,7,Absence
6,56,1,3,130,256,1,2,142,1,0.6,2,1,6,Presence
7,59,1,4,110,239,0,2,142,1,1.2,2,1,7,Presence

In [5]:
df['Age'][0]

np.int64(70)

In [6]:
df[['Age', 'BP']]

     Age   BP
0     70  130
1     67  115
2     57  124
3     64  128
4     74  120
..   ...  ...
265   52  172
266   44  120
267   56  140
268   57  140
269   67  160

[270 rows x 2 columns]

In [7]:
df[['Age', 'BP']][0:4]

   Age   BP
0   70  130
1   67  115
2   57  124
3   64  128

In [8]:
# loc is used for location based indexing and iloc for index based

In [9]:
df.loc[0,["Age", "BP", "Sex"]]

Age     70
BP     130
Sex      1
Name: 0, dtype: object

In [10]:
df.loc[0:,'Age']

0      70
1      67
2      57
3      64
4      74
       ..
265    52
266    44
267    56
268    57
269    67
Name: Age, Length: 270, dtype: int64

In [11]:
df.iloc[0:10, 0]

0    70
1    67
2    57
3    64
4    74
5    65
6    56
7    59
8    60
9    63
Name: Age, dtype: int64

In [12]:
df.iloc[0:5, [0,3]]

   Age   BP
0   70  130
1   67  115
2   57  124
3   64  128
4   74  120

In [13]:
# at and iat is used for to get a particular (single) value. it is just like a loc and iloc but used for tp get a single value

In [14]:
df.iat[0,0]

np.int64(70)

In [15]:
df.at[0,'BP']

np.int64(130)

In [16]:
df.at[0, 'Age']

np.int64(70)

# Filtering

In [17]:
df

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence

In [18]:
df[df['Age'] > 70]

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
15,71,0,4,112,149,0,0,125,0,1.6,2,0,3,Absence
29,71,0,3,110,265,1,2,130,0,0.0,1,1,3,Absence
73,76,0,3,140,197,0,1,116,0,1.1,2,0,3,Absence
199,77,1,4,125,304,0,2,162,1,0.0,1,3,3,Presence
255,71,0,2,160,302,0,0,162,0,0.4,1,2,3,Absence

In [19]:
df[df['Age'] > 70]['BP']

4      120
15     112
29     110
73     140
199    125
255    160
Name: BP, dtype: int64

In [20]:
df[df['Age'] > 69][['Age', 'BP']]

     Age   BP
0     70  130
4     74  120
15    71  112
29    71  110
72    70  156
73    76  140
189   70  160
191   70  145
199   77  125
255   71  160

In [21]:
df[(df['Age'] >= 70) & (df['BP'] > 130)]

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
72,70,1,2,156,245,0,2,143,0,0.0,1,0,3,Absence
73,76,0,3,140,197,0,1,116,0,1.1,2,0,3,Absence
189,70,1,3,160,269,0,0,112,1,2.9,2,1,7,Presence
191,70,1,4,145,174,0,0,125,1,2.6,3,0,7,Presence
255,71,0,2,160,302,0,0,162,0,0.4,1,2,3,Absence

In [22]:
df.query("Age > 72") #query is also used for filtering but has some rules:
# we can't use &,|,! as logical operator we use and,or,not

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
73,76,0,3,140,197,0,1,116,0,1.1,2,0,3,Absence
199,77,1,4,125,304,0,2,162,1,0.0,1,3,3,Presence

In [23]:
df.query("Age >= 70 and BP > 130")

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
72,70,1,2,156,245,0,2,143,0,0.0,1,0,3,Absence
73,76,0,3,140,197,0,1,116,0,1.1,2,0,3,Absence
189,70,1,3,160,269,0,0,112,1,2.9,2,1,7,Presence
191,70,1,4,145,174,0,0,125,1,2.6,3,0,7,Presence
255,71,0,2,160,302,0,0,162,0,0.4,1,2,3,Absence

In [24]:
# if we want to check string value then write that in single quotes
# we can't use space in column name we need to use back ticks(`)
# if we have column name or file name same as any function name, module name, then use that name inside the bacj ticks(``)
df.query("Age >= 70 and BP >= 130 and `Heart Disease` == 'Presence'")

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
189,70,1,3,160,269,0,0,112,1,2.9,2,1,7,Presence
191,70,1,4,145,174,0,0,125,1,2.6,3,0,7,Presence

In [25]:
# if we want to use a variable so we use @ for varibale name 
age =69
df.query("Age > @age")

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
15,71,0,4,112,149,0,0,125,0,1.6,2,0,3,Absence
29,71,0,3,110,265,1,2,130,0,0.0,1,1,3,Absence
72,70,1,2,156,245,0,2,143,0,0.0,1,0,3,Absence
73,76,0,3,140,197,0,1,116,0,1.1,2,0,3,Absence
189,70,1,3,160,269,0,0,112,1,2.9,2,1,7,Presence
191,70,1,4,145,174,0,0,125,1,2.6,3,0,7,Presence
199,77,1,4,125,304,0,2,162,1,0.0,1,3,3,Presence
255,71,0,2,160,302,0,0,162,0,0.4,1,2,3,Absence

In [26]:
df.query("Age >= 70 and `Heart Disease` == 'Presence'")[['Age', 'BP', 'Heart Disease']]

     Age   BP Heart Disease
0     70  130      Presence
189   70  160      Presence
191   70  145      Presence
199   77  125      Presence

In [27]:
# Query functions rules:

# 1. Column names become variables
# You can reference column names directly in the query string:

# df.query("age > 25 and city == 'Delhi'")



# 2. String values must be in quotes
# Use single or double quotes around strings in the expression:

# df.query("name == 'Harry'")



# If you have quotes inside quotes, mix them:

# df.query('city == "Mumbai"')



# 3. Use backticks for column names with spaces or special characters
# If a column name has spaces, use backticks (`):

# df.query("`first name` == 'Alice'")



# 4. You can use @ to reference Python variables
# To pass external variables into .query():

# age_limit = 30
# df.query("age > @age_limit")



# 5. Logical operators
# Use these:

# and, or, not — instead of &, |, ~
# ==, !=, <, >, <=, >=
# Bad:

# df.query("age > 30 & city == 'Delhi'")  # ❌

# Good:

# df.query("age > 30 and city == 'Delhi'")  # ✅



# 6. Chained comparisons
# Just like Python:

# df.query("25 < age <= 40")



# 7. Avoid using reserved keywords as column names
# If you have a column named class, lambda, etc., you’ll need to use backticks:

# df.query("`class` == 'Physics'")



# 8. Case-sensitive
# Column names and string values are case-sensitive:

# df.query("City == 'delhi'")  # ❌ if actual value is 'Delhi'



# 9. .query() returns a copy, not a view
# The result is a new DataFrame. Changes won't affect the original unless reassigned:

# filtered = df.query("age < 50")