In [1]:
import pandas as pd

In [2]:
df =  pd.read_csv('https://codewithharry.nyc3.cdn.digitaloceanspaces.com/dashboard/lesson/data-cleaning-preprocessing-1745500885184/1745501008647-data_cleaning_sample.csv')

In [3]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8 non-null      object
 1   Age        6 non-null      float64
 2   City       9 non-null      object
 3   Gender     9 non-null      object
 4   Email      9 non-null      object
 5   Join Date  8 non-null      object
dtypes: float64(1), object(5)
memory usage: 564.0+ bytes

In [5]:
df.isna() #df.isnull() both are same

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [6]:
df.isnull().sum() #gives no. of null/NaN values in every columns

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [7]:
df.dropna() #for rows

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [8]:
df.dropna(axis=1) #for columns

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [9]:
df['Age'].fillna(df['Age'].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [10]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [11]:
df.ffill(inplace=True)
# df.bfill()

In [12]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

# Duplicate Data

In [13]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [14]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019

# string Functions

In [15]:
df.duplicated(subset=['Name', 'Age'])

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [16]:
df['City'].str.contains('delhi', case=False)
# this function returns is delhi present in city or not 
# case = False    meas case sensitive  (Delhi == delhi ==DeLhi)
#case = True     Delhi == Delhi   (delhi != Delhi)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [17]:
df[df['City'].str.contains('delhi', case=False)]

      Name   Age   City Gender            Email   Join Date
1  Charlie  25.0  Delhi      M  charlie@example  20-07-2021
3  Charlie  30.0  Delhi      M  charlie@example  20-07-2021
5    David  28.0  Delhi      F   eve@domain.com  12-11-2019
8  Charlie  25.0  Delhi      M  charlie@example  20-07-2021

In [18]:
df['Name'].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5      david
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [19]:
df['Email'].str.split('@')

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

# Type conversion

In [20]:
df['Age'] = df['Age'].astype('int64')
# if any value in age column are null/Nan then we can't do type conversiion we need to drop null or fill null after that we can do type conversion. whenever it will gives eIOError

In [21]:
# df['Join DateDate'] = pd.to_datetime(df['Join Date'])
# used to convert date time format
pd.to_datetime(df['Join Date'], format='%d-%m-%Y')

0   2021-05-01
1   2021-07-20
2   2020-06-15
3   2021-07-20
4   2019-11-12
5   2019-11-12
6   2021-05-01
7   2021-05-01
8   2021-07-20
Name: Join Date, dtype: datetime64[ns]

# some important function

In [22]:
df['Age Group'] = df['Age'].apply(lambda x: 'Adult' if x >= 25 else 'Minor')

In [23]:
df

      Name  Age         City Gender              Email   Join Date Age Group
0    Alice   25     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   25        Delhi      M    charlie@example  20-07-2021     Adult
2      Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   30        Delhi      M    charlie@example  20-07-2021     Adult
4    David   22       Mumbai      M  david@example.com  12-11-2019     Minor
5    David   28        Delhi      F     eve@domain.com  12-11-2019     Adult
6    Alice   25     New York      F  alice@example.com  01-05-2021     Adult
7    Alice   25     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   25        Delhi      M    charlie@example  20-07-2021     Adult

In [24]:
gender = {'M' : 'Male', 'F' : 'Female'}
df['Gender'] = df['Gender'].map(gender)

In [25]:
df

      Name  Age         City  Gender              Email   Join Date Age Group
0    Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
1  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Adult
2      Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  Charlie   30        Delhi    Male    charlie@example  20-07-2021     Adult
4    David   22       Mumbai    Male  david@example.com  12-11-2019     Minor
5    David   28        Delhi  Female     eve@domain.com  12-11-2019     Adult
6    Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
7    Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
8  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Adult

In [26]:
df['City'] = df['City'].replace({'Delhi' : 'New Delhi', 'New York' : 'Chandigarh'})

In [27]:
df

      Name  Age         City  Gender              Email   Join Date Age Group
0    Alice   25   Chandigarh  Female  alice@example.com  01-05-2021     Adult
1  Charlie   25    New Delhi    Male    charlie@example  20-07-2021     Adult
2      Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  Charlie   30    New Delhi    Male    charlie@example  20-07-2021     Adult
4    David   22       Mumbai    Male  david@example.com  12-11-2019     Minor
5    David   28    New Delhi  Female     eve@domain.com  12-11-2019     Adult
6    Alice   25   Chandigarh  Female  alice@example.com  01-05-2021     Adult
7    Alice   25   Chandigarh  Female  alice@example.com  01-05-2021     Adult
8  Charlie   25    New Delhi    Male    charlie@example  20-07-2021     Adult