In [1]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [2]:
# if we want to "melt" the DataFrame so that each row represents a student-subject pair, we can do:
a = df.melt(id_vars='Name', value_vars=['Math', 'Science', 'English'], var_name='Subject', value_name='Score')

In [3]:
a

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [4]:
# Explanation:
# id_vars=["Name"]: We keep the "Name" column as it is because it's the identifier.
# value_vars=["Math", "Science", "English"]: These are the columns we want to melt.
# var_name="Subject": The new column containing the names of the subjects.
# value_name="Score": The new column containing the scores.
# Why Use melt()?
# Data normalization: Helps in transforming data for statistical modeling and data visualization.
# Pivot tables: Many times, plotting functions or statistical models work better with long-format data.
# This is useful for converting columns into rows — perfect for plotting or tidy data formats.

In [5]:
a.pivot(index="Name", columns="Subject", values="Score") # pivot is opposite of the melt

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89

In [6]:
# Explanation:
# index="Name": The unique values in the "Name" column will become the rows in the new DataFrame.
# columns="Subject": The unique values in the "Subject" column will become the columns in the new DataFrame.
# values="Score": The values from the "Score" column will populate the table.
# Why use pivot()?
# Better data structure: It makes data easier to analyze when you have categories that you want to split into multiple columns.
# Easier visualization: Often, you want to represent data in a format where categories are split across columns (for example, when creating pivot tables for reporting).
# Aggregating data: You can perform aggregations (like sum, mean, etc.) to group values before pivoting.

In [7]:
# We can use pivot_table() to aggregate values (e.g., taking the mean for duplicate entries):
a.pivot_table(index="Name", columns="Subject", values="Score", aggfunc="mean")

Subject  English  Math  Science
Name
Alice       88.0  85.0     90.0
Bob         85.0  78.0     82.0
Charlie     94.0  92.0     89.0