In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [3]:
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [6]:
df.groupby("Department")['Salary'].mean()

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [8]:
df.groupby('Department')['Team'].count()

Department
HR           2
IT           2
Marketing    2
Sales        2
Name: Team, dtype: int64

In [9]:
df.groupby("Team")['Salary'].sum()

Team
A    175
B    163
C    180
D    155
Name: Salary, dtype: int64

In [10]:
df.groupby("Team")['Salary'].min()

Team
A    85
B    78
C    88
D    75
Name: Salary, dtype: int64

In [11]:
df.groupby("Department")['Salary'].max()

Department
HR           90
IT           85
Marketing    92
Sales        80
Name: Salary, dtype: int64

In [13]:
# .aggregate and .agg functions are same 
df.groupby("Department")[['Salary', 'Age']].agg(['mean', 'min', 'max'])

           Salary           Age
             mean min max  mean min max
Department
HR           87.5  85  90  24.0  23  25
IT           81.5  78  85  26.0  22  30
Marketing    90.0  88  92  27.0  26  28
Sales        77.5  75  80  24.0  21  27

In [14]:
# we can also change column name 
df.groupby("Department")['Salary'].aggregate(avg_mean='mean')

            avg_mean
Department
HR              87.5
IT              81.5
Marketing       90.0
Sales           77.5

In [15]:
df.groupby("Team").agg({
    "Salary": "mean",
    "Age": "max"
})

      Salary  Age
Team
A       87.5   25
B       81.5   30
C       90.0   28
D       77.5   27

In [16]:
df['Mean_avg'] = df.groupby('Team')['Salary'].transform("mean")

In [17]:
df

  Department Team Gender  Salary  Age   JoinDate  Mean_avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
2         IT    B      M      78   30 2021-03-20      81.5
3         IT    B      F      85   22 2021-04-10      81.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0
6      Sales    D      M      75   21 2021-07-15      77.5
7      Sales    D      F      80   27 2021-08-01      77.5

In [20]:
df.groupby("Department").filter(lambda x: x['Salary'].mean() > 85)

  Department Team Gender  Salary  Age   JoinDate  Mean_avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0