In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [5]:
pd.merge(employees, departments, on="DeptID") 
# inner join by default 
# it merge the data which is common on both. in it we are merging the data by DeptID so it give DeptID that is common on both

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [6]:
pd.merge(employees, departments, on="DeptID", how="left")
# here in left we place employees and in right we place the departments we want on deptid which is present in employees(left)

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [7]:
pd.merge(employees,departments,on="DeptID", how="right")
# here we want values from departments which is placed on right so we use how=right

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [8]:
pd.merge(employees,departments,on="DeptID", how="outer")
# it merges all the data

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [12]:
# df.merge(df, left_on='managerId', right_on='id', suffixes=("_emp", "_man"))
# output
# id_emp	name_emp	salary_emp	managerId_emp	id_man	name_man	salary_man	managerId_man
# 	1	     Joe	      70000	        3	          3	      Sam	      60000	     <NA>
# 	2	    Henry         80000	        4	          4	      Max	      90000	     <NA>

In [9]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

pd.concat([df1, df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [10]:
pd.concat([df1,df2], axis=1)

    Name     Name
0  Alice  Charlie
1    Bob    David