In [53]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [54]:
df = pd.read_csv("train.txt", sep=";", header=None, names=['text', 'emotion'])
# the file is in txt form and we are reading it as csv because the content of file is 
# separated via ; so it separates the data using ; and we use header = None because
# it prevent to make a first sentence as a header if we don't use this it will take the 
# first line of the file as heading

In [55]:
df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In this we only learn about first two phase of NLP pipeline

1. data collection - collecting data from various source
2. cleaning and process data

now lets understanding how do we prepare or clean the data for machine learning model

# cleaning data
there are some steps which use to clean data and prepare it of model

steps:-

1. lowercasing - converting all text in lower case because model will differentiate
                  "The" and "the"

2. removing punctuation - Removing punctuation (!,@#$ etc.) because they don't add
                         meaning in ML context. But if we are using deep learning
                         then we don't remove puntuation.

3. remove numbers - removing digits from the text('i have 5 phones' -> 'i have phones')

4. remove urls and html tags

5. remove emojis and special characters - images uses unicode values(utf) and we can
                             eliminate by considering ASCII value of characters only

6. remove stopwords - one of the most important step removing repitative word which
                      don't carry any meaning eg. is, are,the, have
(chandigarh is the city beautiful -> chandigarh city beautiful)

In [56]:
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [57]:
# now we can easily convert the emotion into numeric value because ml model is interpret only with numbers 
unique_emo = df['emotion'].unique()
emotions = {}
i = 0
for emotion in unique_emo: 
    emotions[emotion] = i 
    i += 1

df['emotion'] = df['emotion'].map(emotions)

In [58]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [59]:
# now for text content cour first step is to lowercase the text 
# as in our dataset there is all data already in lowercase but we can do lowercasing
# to understanding concepts

df['text'] = df['text'].apply(lambda x : x.lower())

In [60]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [61]:
# now the next step is to removing the punctuations 
# so for removing the punctuation we are using string library 

import string 

def rem_punt(txt):
    return txt.translate(str.maketrans("","",string.punctuation))

# string.punctuation: This is a built-in Python constant that contains a string of all
# standard ASCII punctuation symbols (e.g., ! " # \$ % & ' ( ) * + , - )
# .str.maketrans("", "", string.punctuation): This function creates a translation 
# dictionary. By providing three arguments, you instruct Python to map the characters
# in the third string to None. This tells Python to delete every punctuation mark found
# in the text.text.translate(...): This method applies the translation map to your 
# string, returning a brand new string with all of the mapped characters
# (the punctuation marks) completely deleted.


df['text'] = df['text'].apply(rem_punt)

In [62]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [63]:
# now removing numbers 

def rem_no(txt): 
    new = ""
    for i in txt:
        if not i.isdigit(): 
            new = new + i 
    return new 


df['text'] = df['text'].apply(rem_no)

In [64]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [65]:
# removing emoji 
def rem_emo(txt): 
    new = ""
    for i in txt: 
        if i.isascii():
            new = new + i 
    return new 

df['text'] = df['text'].apply(rem_emo)

In [42]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [73]:
# removing stopwords 
# for removing stopwords we are using nltk library

import nltk
from nltk.corpus import stopwords # corpus means collection of words
from nltk.tokenize import word_tokenize

# each individual word refers as token 
# and the process of splitting the sentence into tokens called tokenization
# we can also use .split() for splitting the words 
# eg = ['hi', 'i', 'am', 'aman']

nltk.download('punkt') # use to split the text into tokens
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /Users/amarjeet/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/amarjeet/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/amarjeet/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [74]:
# now lets see stopwords 
len(set(stopwords.words('english')))
# there is 198 stopwords in english language we can see them by removing len()

198

In [76]:
# lets remove the stopwords and separate the tokens 
stop_word = set(stopwords.words('english'))

def tokenization(txt): 
    texts = word_tokenize(txt)
    tokens = []

    for i in texts: 
        if i not in stop_word: 
            tokens.append(i)
    return " ".join(tokens) #we are using .join() because it convert that list into string

df['text'] = df['text'].apply(tokenization)

In [77]:
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]