In [1]:
import pandas as pd 
import requests 
from bs4 import BeautifulSoup

In [2]:
url = "https://www.ambitionbox.com/it-services-and-consulting-companies-in-india"

In [3]:
headers = {"User-Agent" : "Mozilla/5.0"}

In [4]:
response = requests.get(url, headers=headers)

In [5]:
response

In [6]:
soup = BeautifulSoup(response.content, "html.parser")

In [8]:
# print(soup.prettify())

In [10]:
companies = soup.find_all('div', class_ = 'LocCollections__companyName')
company = []
for comp in companies: 
    company.append(comp.text.strip())

In [11]:
company

['Presidio Solutions Pvt Ltd',
 'Xperteez Technology',
 'ThoughtSol Infotech Limited',
 'Techwise Digital',
 'Valuesoft Info Services',
 'Vatsal Technosoft',
 'Innover Digital',
 'BGD Tech PVT LTD',
 'Alpha Net Consulting',
 'Quadrasystems Net']

In [34]:
ratings = soup.find_all('div', class_ = "rating_text rating_text--sm")
rating = []
for rate in ratings: 
    rating.append(float(rate.text.strip()))

In [26]:
reviews = soup.find_all('span', class_ = 'LocCollections__companyRatingCount')
review = [] 
for rev in reviews: 
    review.append(int(rev.text.strip().split()[0].replace('(', '').strip()))

In [27]:
review

[155, 111, 555, 121, 83, 111, 309, 196, 144, 77]

In [35]:
rating

[4.7, 4.8, 4.6, 4.7, 4.7, 4.5, 4.3, 4.4, 4.6, 4.4]

In [42]:
logos_html = soup.find_all('a', class_ = 'LocCollections__card')

In [43]:
logos = [logo.find('img')['src'] for logo in logos_html]

In [44]:
logos

['https://static.ambitionbox.com/alpha/company/photos/logos/presidio-solutions-d.jpg',
 'https://static.ambitionbox.com/alpha/company/photos/logos/xperteez-technology.jpg',
 'https://static.ambitionbox.com/alpha/company/photos/logos/thoughtsol-infotech.jpg',
 'https://static.ambitionbox.com/alpha/company/photos/logos/techwise-digital.jpg',
 'https://static.ambitionbox.com/alpha/company/photos/logos/value-soft-solutions.jpg',
 'https://static.ambitionbox.com/alpha/company/photos/logos/vatsal-technosoft.jpg',
 'https://static.ambitionbox.com/alpha/company/photos/logos/innover-digital.jpg',
 'https://static.ambitionbox.com/alpha/company/photos/logos/bgd-tech.jpg',
 'https://static.ambitionbox.com/alpha/company/photos/logos/alpha-net-consulting.jpg',
 'https://static.ambitionbox.com/alpha/company/photos/logos/quadrasystems-net.jpg']

In [46]:
data = [] 
for com, rev, rat, log in zip(company, review, rating, logos): 
    data.append({"company" : com, 
                "rating" : rat,
                 "review" : rev,
                 "logo" : log
                })

In [47]:
df = pd.DataFrame(data)

In [48]:
df

,company,rating,review,logo
0,Presidio Solutions Pvt Ltd,4.7,155,https://static.ambitionbox.com/alpha/company/p...
1,Xperteez Technology,4.8,111,https://static.ambitionbox.com/alpha/company/p...
2,ThoughtSol Infotech Limited,4.6,555,https://static.ambitionbox.com/alpha/company/p...
3,Techwise Digital,4.7,121,https://static.ambitionbox.com/alpha/company/p...
4,Valuesoft Info Services,4.7,83,https://static.ambitionbox.com/alpha/company/p...
5,Vatsal Technosoft,4.5,111,https://static.ambitionbox.com/alpha/company/p...
6,Innover Digital,4.3,309,https://static.ambitionbox.com/alpha/company/p...
7,BGD Tech PVT LTD,4.4,196,https://static.ambitionbox.com/alpha/company/p...
8,Alpha Net Consulting,4.6,144,https://static.ambitionbox.com/alpha/company/p...
9,Quadrasystems Net,4.4,77,https://static.ambitionbox.com/alpha/company/p...

In [53]:
image_paths = [] 

for i, url in enumerate(logos): 
    img_data = requests.get(url).content
    path = f"logos/logo{i}.png"

    with open(path, 'wb') as f:
        f.write(img_data)

    image_paths.append(path)
# df['logo_path'] = image_paths
    df['image'] = img_data

In [54]:
df

,company,rating,review,logo,logo_path,image
0,Presidio Solutions Pvt Ltd,4.7,155,https://static.ambitionbox.com/alpha/company/p...,logos/logo0.png,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
1,Xperteez Technology,4.8,111,https://static.ambitionbox.com/alpha/company/p...,logos/logo1.png,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
2,ThoughtSol Infotech Limited,4.6,555,https://static.ambitionbox.com/alpha/company/p...,logos/logo2.png,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
3,Techwise Digital,4.7,121,https://static.ambitionbox.com/alpha/company/p...,logos/logo3.png,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
4,Valuesoft Info Services,4.7,83,https://static.ambitionbox.com/alpha/company/p...,logos/logo4.png,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
5,Vatsal Technosoft,4.5,111,https://static.ambitionbox.com/alpha/company/p...,logos/logo5.png,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
6,Innover Digital,4.3,309,https://static.ambitionbox.com/alpha/company/p...,logos/logo6.png,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
7,BGD Tech PVT LTD,4.4,196,https://static.ambitionbox.com/alpha/company/p...,logos/logo7.png,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
8,Alpha Net Consulting,4.6,144,https://static.ambitionbox.com/alpha/company/p...,logos/logo8.png,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
9,Quadrasystems Net,4.4,77,https://static.ambitionbox.com/alpha/company/p...,logos/logo9.png,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...